[tool.poetry]
name = "shap-clustering"
version = "0.1.0"
description = ""
authors = ["Rafael Dias <rafaelagd@gmail.com>"]
readme = "README.md"
packages = [{include = "shap_clustering"}]

[tool.poetry.dependencies]
python = "^3.8.10"
shap = "^0.41.0"
pycaret = "^2.3.10"
numpy = "1.23"
nbformat = "^5.7.3"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
isort = "^5.12.0"
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
mypy = "^1.1.1"
types-requests = "^2.28.11.15"
coverage = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
