name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos do repo
        uses: actions/checkout@v3

      - name: Install python version 3.8.16
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'

      - name: Update pip
        run: pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Poetry restore lock file
        run: poetry lock
      
      - name: Poetry install dependencies
        run: poetry install
      
      - name: Run tests
        run: poetry run pytest --cov=src --cov-report=xml
      
      
    